[package]
name = "n-flashthing"
version = "0.5.0"
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.44"
flashthing = { path = "../lib" }
pollster = "1.0.1"

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dependencies.napi]
version = "3.9"
default-features = false
features = ["napi4", "async"]

[dependencies.napi-derive]
version = "3.5"
features = ["type-def"]

[build-dependencies]
napi-build = "2"
